#!/usr/bin/env ruby
require 'craff_palindrome'
require 'open-uri'
require 'FileUtils'

palindromes = URI.open('https://cdn.learnenough.com/phrases.txt').readlines.select(&:palindrome?)

palindromes.each { |palindrome| puts "palindrome detected: #{palindrome}" }

if File.exists?("palindromes_url.txt")
  FileUtils.rm("palindromes_url.txt")
end

File.write('palindromes_url.txt', palindromes.join)
